### ISSUE TITLE
Support hierarchical paths for repositories (user/repo-name)

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#178]
Currently, artipie supports flat repo structure - repo path can contain just single part. For the `central.artipie.com` it will be better to use two-level hierarchy `<user>/<repo>`. 
We need to support multilevel paths in artipie

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak I think it's a good idea, with such approach we need to think how to configure admin permissions for each `user` repository namespace, i.e. we need some `admin` user who can manage repositories inside his namespace. E.g. we can create repository permissions config to manage this:
```yaml
repository:
  permissions:
    user1:
      # can create and edit repo configs
      - admin
```
at:
```
root
 +-user1
 |   + _repository.yml # repository configuration
 |   + repo1.yml
 |   + repo2.yml
 +-user2
     + _repository.yml # repository configuration
     + repo1.yml
     + repo2.yml
```
Alternatively, we can assume that user with `user1` username is owner of all repositories under `user1/*` path and can edit it delete and add new. But it may lead to uncontrolled access to Artipie, since any user will be able to create new repositories.

@artipie/contributors what do you think? Can it break something in existing repos? Do you have some suggestions?

**Comment by olenagerasimova** [comment]
@g4s8 I'd suggest to support same structure for repository permissions config as for repo config: 
```yaml
repository:
  permissions:
    john:
      - read
    jane:
      - write
```
Permissions set can be whatever we like/need. Thus yaml setting structure will be unified, settings will be more flexible and we will not need to define roles (like `admin` in your case).

Also I'd suggest to come up with some proper names for the config files, now we can get lost in them ourselves (`repository` and `repo` sounds very similar)...

**Comment by g4s8** [comment]
@olenagerasimova yes, I wrote the same example (but with `user` and `user2` instead of `john` and `jane`), just with different permission name. The main question is: what the user can do with these permissions, e.g. I thought `admin` permission allows user to create, edit and delete repositories in a namespace. So what the `read` permission allows then?

> Also I'd suggest to come up with some proper names for the config files, now we can get lost in them ourselves (repository and repo sounds very similar)...

Yes, as I know all configurations uses `repository` or `repositories` names. `repo1` and `repo2` in the example is just a name of repository to demonstrate the layout structure.

**Comment by olenagerasimova** [comment]
@g4s8 I failed to see that `admin` is a permission name in your example, I thought it was some role, sorry. Maybe we can use asterisk sign instead of `admin`, `*` would mean that any possible action is allowed. We also can have `create`, `edit` and `delete` permissions, may be some users will only be allowed to create repos, but not edit and delete them.

**Comment by 0crat** [comment]
The job [#178](https://github.com/artipie/artipie/issues/178) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/89588559-2c2c-4386-b384-53e4858cf78d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`

**Comment by jeffzhu503** [comment]
If you support multiple tenants, you might consider more than 2 levels. For example:
/myorg/myusername/repo-name

**Comment by g4s8** [comment]
@jeffzhu503 please see #196 ticket

**Comment by g4s8** [comment]
Fixed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@773dc7f8-970d-444a-b02a-c8dba678f128, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/artipie#178" exists in boosts.xml, but the job is absent in the WBS among 65 jobs.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [2d425575-a794-4b4e-8a87-676cfddc5e72](https://www.0crat.com/footprint/CT2E6TK9B/2d425575-a794-4b4e-8a87-676cfddc5e72), Type: "Remove job from WBS"
