### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by cambierr** [artipie/artipie#392]
To be able to deploy artipie in Kubernetes environments (for instance, using helm charts), it would be a really nice things to benefit from a health check endpoint to be able to monitor the application state and trigger some self-healing & scaling if needed.

To be more precise, I'd suggest to take inspiration from gitlab for instance: https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html

Any though on this ? like what should be taken into account to report a 100% UP check ? storages availability ? correct configuration ?a per-repository heath check interface to be able to report a global healthiness view ? ...?

**Comment by jeffzhu503** [comment]
Yes, the service needs to expose these end points for monitoring purpose, even without using Kubernetes. Copy from the gitlab link from the above.  
GET http://localhost/-/health
GET http://localhost/-/readiness
GET http://localhost/-/liveness

**Comment by g4s8** [comment]
@cambierr thanks for reporting, we definitely need health-check endpoints for k8s.
> Any though on this ? like what should be taken into account to report a 100% UP check ? storages availability ? correct configuration ?a per-repository heath check interface to be able to report a global healthiness view ? ...?

Storages availability - we can check repository configuration storage availability for the health-check, but I'd not check repository storages, since it may take a while.

Correct configuration - it's not needed if we check "Storage availability", since configuration will be parsed and validated to read storage config

A per-repository heath check - I don't think it's a good idea for some reasons: 1) if one repository is broken, we shouldn't stop other repositories which may be used 2) it could be a long-running operation if we have a lot of repositories

@jeffzhu503 @cambierr so I'd go with first option: checking main storage availability (which includes main configuration validation), WDYT?

**Comment by g4s8** [comment]
@cambierr @jeffzhu503 health check endpoint was implemented in #458 PR.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#392` is not assigned, can't get performer
