### ISSUE TITLE
Dockerfile is extremely long to build

### ISSUE THREAD

**Issue by victornoel** [artipie/artipie#63]
I noticed the Dockerfile is extremely long to build, it looks like it is downloading the whole internet even though it's not needed when one just want to build the package.

I propose to:
- not call `dependency:go-offline`
  - it's useless since it is used for building the package 1 second later...
  - when calling `mvn package`, it will download only the needed dependencies.
- skip tests, qulice and stuffs like that, it's not needed to build the image, the CI is already protecting us from it

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, it should be fixed with #205

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#63` is not assigned, can't get performer

**Comment by victornoel** [comment]
@g4s8 actually it doesn't, you kept the go offline and didn't skip tests and stuffs

**Comment by g4s8** [comment]
> @g4s8 actually it doesn't, you kept the go offline and didn't skip tests and stuffs

@victornoel see https://github.com/artipie/artipie/blob/master/Dockerfile - there are no `go-offline` anymore. Also, all dependencies are predownloaded from base image. The only command to build jar file is:
```dockerfile
RUN mvn versions:set -DnewVersion=${version} && \
  mvn package -P assembly
```

**Comment by victornoel** [comment]
@g4s8 so if the pom change, I need to rebuild the base image?

**Comment by g4s8** [comment]
@victornoel no, it's a well known Maven/Docker trick: you're creating base image with dependencies for the project, and if any project dependency change it will be downloaded from internet, but the amount of changed dependencies will be much fewer than bundled dependencies cache, since the majority of dependencies are plugins with dependencies, dependencies of dependencies and so on, you `pom` dependencies are about only 3-5% from all downloaded jars. So you can rebuild base image once a year to keep it up to date.

**Comment by victornoel** [comment]
@g4s8 interesting, thanks for the explanation
